version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8.0.25
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo

volumes:
  db_data: